version: '2'

services:
  nginx:
    image: docker.wouterdeschuyter.be/ikhaat.be/nginx
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.beikaat.redirectscheme.scheme=https"
      - "traefik.http.routers.beikaat-http.rule=Host(`ikhaat.be`)"
      - "traefik.http.routers.beikaat-http.entrypoints=web"
      - "traefik.http.routers.beikaat-http.middlewares=beikaat"
      - "traefik.http.routers.beikaat.rule=Host(`ikhaat.be`)"
      - "traefik.http.routers.beikaat.entrypoints=websecure"
      - "traefik.http.routers.beikaat.tls.certresolver=myhttpchallenge"
    networks:
      - default
      - reverse-proxy

  php-fpm:
    image: docker.wouterdeschuyter.be/ikhaat.be/php-fpm
    restart: unless-stopped
    networks:
      - default

networks:
  reverse-proxy:
    external: true
