version: '2'

services:
  nginx:
    image: docker.wouterdeschuyter.be/ikhaat-website-nginx
    restart: unless-stopped
    environment:
      - LETSENCRYPT_EMAIL=wouter.de.schuyter@gmail.com
    networks:
      - default
      - webproxy
    logging:
      options:
        max-size: 2m
        max-file: '5'

  php-fpm:
    image: docker.wouterdeschuyter.be/ikhaat-website-php-fpm
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./.env:/code/.env:ro
    networks:
      - default
      - webproxy
    logging:
      options:
        max-size: 2m
        max-file: '5'

networks:
  webproxy:
    external: true
