version: '2'

services:
  nginx:
    image: docker.pkg.github.com/wouterds/ikhaat.be/nginx
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=ikhaat.be
      - LETSENCRYPT_HOST=ikhaat.be
      - LETSENCRYPT_EMAIL=wouter.de.schuyter@gmail.com
    networks:
      - default
      - webproxy

  php-fpm:
    image: docker.pkg.github.com/wouterds/ikhaat.be/php-fpm
    restart: unless-stopped
    networks:
      - default
      - webproxy

networks:
  webproxy:
    external: true
