version: '2'

services:
  nginx:
    image: docker.wouterdeschuyter.be/ikhaat-website-nginx
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=ikhaat.be
      - LETSENCRYPT_HOST=ikhaat.be
      - LETSENCRYPT_EMAIL=wouter.de.schuyter@gmail.com
    networks:
      - default
      - webproxy

  php-fpm:
    image: docker.wouterdeschuyter.be/ikhaat-website-php-fpm
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./.env:/code/.env:ro
    networks:
      - default
      - webproxy

networks:
  webproxy:
    external: true
