version: '2'

services:
  nginx:
    image: nginx:1.15-alpine
    env_file:
      - ./../.env
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./..:/code

  php-fpm:
    build:
      context: ./..
      dockerfile: ./.docker/php-fpm/Dockerfile
    env_file:
      - ./../.env
    volumes:
      - ./..:/code
